# AgentMesh Config

# Model config
models:
  openai:
    api_base: "https://api.openai.com/v1"
    api_key: "YOUR_API_KEY"
    models: [ "gpt-4.1", "gpt-4o", "gpt-4.1-mini" ]

  claude:
    api_key: "YOUR_API_KEY"
    models: [ "claude-3-7-sonnet-latest" ]


# Tool config
tools:
  google_search:
    # get your apikey from https://serper.dev/
    api_key: "YOUR_SERPER_API_KEY"


# Team config
teams:
  search_team:
    model: "gpt-4.1-mini"
    description: "A Search Assistant Team"
    agents:
      - name: "Search Assistant"
        description: "Searching by operating the browser"
        system_prompt: "You are a browser operation assistant, completing user tasks by operating the browser"
        tools:
          - time
          - google_search
          - browser
          - file_save

  software_team:
    model: "gpt-4.1"
    description: "A software development team with product manager, developer and tester."
    rule: "A normal R&D process should be that Product Manager writes PRD, Developer writes code based on PRD, and Finally, Tester performs testing."
    max_steps: 20
    agents:
      - name: "Product Manager"
        max_steps: 5
        description: "Responsible for product requirements and documentation"
        system_prompt: "You are an experienced product manager who creates concise PRD. Focus on user needs and feature specifications. Always format your response in Markdown."
        tools:
          - time
          - file_save
      - name: "Developer"
        description: "Implements code based on PRD"
        system_prompt: "You are a proficient developer who writes clean, efficient, and maintainable code."
        tools:
          - time
          - calculator
          - file_save
      - name: "Tester"
        description: "Tests code and verifies functionality"
        system_prompt: "You are a QA tester who validates code against requirements. For HTML code, you can use browser to test functionality. You only need to test a few core cases, the final output is the markdown test report"
        tools:
          - browser
          - file_save
