version: '2.0'

services:
  agentmesh:
    image: minimalfuture/agentmesh
    container_name: agentmesh
    volumes:
      - ./config.yaml:/config/config.yaml
    stdin_open: true  # Enable interactive input
    tty: true         # Allocate a pseudo-TTY
